### PR TITLE
fix: Replace SafeBuffer with Buffer, support BASE64 in the browser

### LINKED ISSUE #70: Safe to remove safe-buffer
bet many have updated their node version already.
Willing to change lowest supported node version to something like LTS and use native `Buffer.from` instead to reduce the size?

Can help you with a PR if you like.

### PR DESCRIPTION
**Pull request by prantlf**
This is a part of changes to get this module usable in the web browser
and more lightweight at the same time.

* Remove the safe-buffer dependency. Use the Buffer constructor and
  Buffer.from depending on what is available.
* Use atob/btoa with a workaround for UTF-8 in the browser.

Fixes #70 without dropping the compatibility with Node.js 0.10.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -16,10 +15,16 @@ Object.defineProperty(exports, 'mapFileCommentRegex', {
...
-function decodeBase64(base64) {
-  return (SafeBuffer.Buffer.from(base64, 'base64') || "").toString();
-}
+var decodeBase64 = typeof Buffer !== 'undefined' ? Buffer.from ?
+  function decodeBase64(base64) {
+    return Buffer.from(base64, 'base64').toString();
+  } :
+  function decodeBase64(base64) {
+    return new Buffer(base64, 'base64').toString();
+  } :
```
Comment (phated) [inline index.js:24]:
```suggestion
  function decodeBase64(base64) {
    if (typeof value === 'number') {
      throw new TypeError('The value to decode must not be of type number.)
    }
    return new Buffer(base64, 'base64').toString();
  } :
```

[safer-buffer](https://github.com/ChALkeR/safer-buffer/blob/master/safer.js#L29-L31) checks to make sure that the value isn't a number (I believe that is because `new Buffer` allocates bytes of length `value` if the value is a number).

File: index.js [hunk 2]
```diff
@@ -16,10 +15,16 @@ Object.defineProperty(exports, 'mapFileCommentRegex', {
...
 });
 
-
-function decodeBase64(base64) {
-  return (SafeBuffer.Buffer.from(base64, 'base64') || "").toString();
-}
+var decodeBase64 = typeof Buffer !== 'undefined' ? Buffer.from ?
+  function decodeBase64(base64) {
+    return Buffer.from(base64, 'base64').toString();
+  } :
```
Comment (phated) [inline index.js:21]: Can we make these `if` statements instead of ternary?

File: index.js [hunk 3]
```diff
@@ -56,10 +61,19 @@ Converter.prototype.toJSON = function (space) {
   return JSON.stringify(this.sourcemap, null, space);
 };
 
-Converter.prototype.toBase64 = function () {
-  var json = this.toJSON();
-  return (SafeBuffer.Buffer.from(json, 'utf8') || "").toString('base64');
-};
+Converter.prototype.toBase64 = typeof Buffer !== 'undefined' ? Buffer.from ?
+  function () {
```
Comment (phated) [inline index.js:65]: Can these be `if` statements too?

**Review by phated — CHANGES_REQUESTED** [review]
This is really awesome and I think we should make the switch! I added some comments inline.

File: index.js (hunk 3 above)
Comment (thlorenz) [reply index.js:65]: Agreed + this function should be declared elsewhere and named and then just referenced here, otherwise it is hard to debug since it'll be anonymous.

Additionally probably should do `Buffer.from.bind(Buffer` just in case in the future that function will refer to `Buffer` as `this`.

**Comment by phated** [comment]
@thlorenz I rebased on top of the GitHub Actions and updated the code based on what we discussed above. Can you take another look?

**Review by phated — APPROVED** [review]
I made the changes so this approval is pretty meaningless 😛

File: index.js [hunk 4]
```diff
@@ -16,9 +15,28 @@ Object.defineProperty(exports, 'mapFileCommentRegex', {
...
+} else {
+  decodeBase64 = decodeBase64WithAtob;
+}
 
-function decodeBase64(base64) {
-  return (SafeBuffer.Buffer.from(base64, 'base64') || "").toString();
+function decodeBase64WithBufferFrom(base64) {
+  return Buffer.from(base64, 'base64').toString();
+}
+function decodeBase64WithNewBuffer(base64) {
```
Comment (thlorenz) [inline index.js:32]: Style: leave a line between these functions

File: index.js [hunk 5]
```diff
@@ -56,10 +74,31 @@ Converter.prototype.toJSON = function (space) {
...
+  Converter.prototype.toBase64 = encodeBase64WithBtoa;
+}
+
+function encodeBase64WithBufferFrom() {
   var json = this.toJSON();
-  return (SafeBuffer.Buffer.from(json, 'utf8') || "").toString('base64');
-};
+  return Buffer.from(json, 'utf8').toString('base64');
+}
+function encodeBase64WithNewBuffer() {
```
Comment (thlorenz) [inline index.js:91]: Ditto line between functions

**Review by thlorenz — CHANGES_REQUESTED** [review]
LGTM aside from the nits.
Feel free to merge once you fix those.
Thanks!

**Comment by thlorenz** [comment]
Some of the CI is failing on this one now .. not sure if it's a fluke, but at any rate we could probably take anything `<=12.0` out of CI (we're basically just wasting electricity with this :) )

**Comment by phated** [comment]
> Some of the CI is failing on this one now .. not sure if it's a fluke, but at any rate we could probably take anything <=12.0 out of CI (we're basically just wasting electricity with this :) )

Windows + node <4 is really flakey. I think we should remove them when we bump the 2.0 major (which I'll begin prepping after we release this). Sound good?
